### ISSUE TITLE
Remove font face mixin

### ISSUE THREAD

**Issue by losbeekos** [losbeekos/basos#42]
Only woff2 and woff need to  be supported so this mixin is obsolete.

Add this in _fonts.scss as a snippet:

```css
@font-face{
    font-family: 'somefont';
    font-style: somestyle;
    font-weight: someweight;
    src: url('../fonts/somefont/somefont-weight.woff2') format('woff2'),
         url('../fonts/somefont/somefont-weight.woff') format('woff')
}
```
