### ISSUE TITLE
Add break-inside modifier to css-column class

### ISSUE THREAD

**Issue by losbeekos** [losbeekos/basos#43]
```css
.css-columns--avoid-column {
   div, ul, ol, p, span {
      break-inside: avoid-column;
   }
}
```
